### PR TITLE
Automate updating 3rd party licenses

### LINKED ISSUE #76: Build is failing per third-party license differences
See https://github.com/erlef/setup-beam/runs/4572138656?check_suite_focus=true as an example.

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Does this seem like a good enough option?

Closes #76.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
I'm purposefully not updating the 3rd party licenses, to have this scheduled action happen on `main`, where it should work.

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira I was more thinking something that just runs a build, we should get notified if it fails. If it fails, then we know we need to update the licenses. 

The thing that I guess makes me nervous about this is nodejs deps 😬 Maybe I'm overly concerned here?

**Comment by paulo-ferraz-oliveira** [comment]
Hm. I'm not worried, since the dependencies are kept by the action container itself. In any case, we can always try and see how it goes, right?

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira Fair enough. Just need to be sure to review commits before release :) 

Can you rebase this so it passes?

**Review by starbelly — APPROVED** [review]

**Comment by paulo-ferraz-oliveira** [comment]
> Can you rebase this so it passes?

Sure. On it.

**Comment by paulo-ferraz-oliveira** [comment]
Some action results are stuck because `ubuntu-16.04` is no longer available. I'm merging as-is and hope the merge of #83 will solve these issues in `main`.

**Comment by paulo-ferraz-oliveira** [comment]
https://github.com/erlef/setup-beam/actions/runs/1687446824 ran and didn't update anything. 😄 I assume it's because there's really nothing to update - we've updated the licenses very recently.

**Pull request merged**
