### PR TITLE
Update Gleam versions in README.md

### PR DESCRIPTION
**Pull request by richard-viney**
# Description

Updates the Gleam examples to reference more recent Gleam and OTP versions.

- [*] I have read and understood the [contributing guidelines](/erlef/setup-beam/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Hey. Thanks for the update. Could you do similar in the tests so we're sure what we're proposing works?

**Comment by richard-viney** [comment]
Have added Gleam 1.5.1 to `.girhub/workflows/{ubuntu,windows}.yml`

**Comment by paulo-ferraz-oliveira** [comment]
Thanks for this. I'll run CI and if tests pass this gets merged.

**Comment by paulo-ferraz-oliveira** [comment]
Is this something you know how to fix in the test files?

https://github.com/erlef/setup-beam/actions/runs/11771918498/job/32831472245?pr=308#step:12:14

**Comment by richard-viney** [comment]
A possible fix has been pushed, I've tested in locally on Gleam 0.23.

**Comment by richard-viney** [comment]
Have pushed another fix.

It might be reasonable to drop support for Gleam versions < v1. Could be one for the next major version bump?

**Comment by paulo-ferraz-oliveira** [comment]
We could merge this, but then the test project is basically useless. I'll try to generate one.

**Comment by paulo-ferraz-oliveira** [comment]
> It might be reasonable to drop support for Gleam versions

If by this you mean stop testing, yeah, I think we can. If something comes up we have an issue tracker and maybe it'll get fixed.

**Review by paulo-ferraz-oliveira — CHANGES_REQUESTED** [review]
Once the pull request I created gets merged, and we re-run CI, I think this'll be good to go.

**Comment by richard-viney** [comment]
Thanks!

**Review by starbelly — APPROVED** [review]
LGTM!

**Comment by paulo-ferraz-oliveira** [comment]
This change was released in [v1.19.0](https://github.com/erlef/setup-beam/releases/tag/v1.19.0), also tagged `v1.19` and `v1` (moved).

**Pull request merged**
