### PR TITLE
Add Erlang 24 to README and some more info on version matching

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
I see there's also a bit on "Authenticating with Postgres in Phoenix" in the README, but I'm not sure it fits there. Should we remove that example?

### CODE REVIEW

**Comment by eproxus** [comment]
Maybe add an example using `>0` as well?

**Comment by paulo-ferraz-oliveira** [comment]
> Maybe add an example using `>0` as well?

Thing is even though it's possible, it's kinda discouraged by the rest of the text: "For best results, we recommend specifying exact Erlang/OTP, Elixir versions, and `rebar3` versions."

Let me hear "the others"; we'll figure something out. 😄 (I've brought this issue up in the past stating that we could also have a flag for `strict-version: true`, in which case we'd bypass the range _finding_).

**Comment by eproxus** [comment]
@paulo-ferraz-oliveira 
> Thing is even though it's possible, it's kinda discouraged by the rest of the text: "For best results, we recommend specifying exact Erlang/OTP, Elixir versions, and `rebar3` versions."

Do you know why it is discouraged? I wondered that already when reading the documentation the first time.

**Comment by ericmj** [comment]
You usually want strict versions in CI to make it reliable. Otherwise you would automatically upgrade to new versions which can have breaking changes or bugs, this can cause issues if your CI is part of your deployment stack or does other critical things.

**Review by ericmj — APPROVED** [review]

**Comment by eproxus** [comment]
@ericmj Got it. Unless convinced otherwise, I would argue it is a good idea to use "latest" if you are developing a library that other people will use with perhaps newer versions than you tested with to get an early warning (of course, nothing prevents you from testing both a specific and a latest version).

**Comment by paulo-ferraz-oliveira** [comment]
I agree with Eric (we've touched this subject elsewhere before): CI needs to be repeatable, _in most cases_. However, if you want to also do CI for e.g. nightly builds, to check if your software is compatible with a new release, this is also a valid use case, and the one where version ranges make the most sense.

**Comment by paulo-ferraz-oliveira** [comment]
@ericmj, any thoughts on getting rid of the Phoenix bit? I'm not sure why it's there, to start with, but it doesn't seem to fit.

**Comment by paulo-ferraz-oliveira** [comment]
@eproxus wrote a nice gist on how to use the action with cache: https://gist.github.com/eproxus/d74315864fd6897bb47741e8de5bc980.

Over Slack he told me he's willing to either incorporate this in the README or create a new (e.g.) EXAMPLE_USAGE.md with basically the same content (via pull request).

We could also just point to his gist. Thoughts?

**Comment by ericmj** [comment]
@paulo-ferraz-oliveira Drop the phoenix part imo.

**Comment by paulo-ferraz-oliveira** [comment]
> @paulo-ferraz-oliveira Drop the phoenix part imo.

Done: https://github.com/erlef/setup-beam/pull/45/commits/5b6c41fe4a7b4ecf6eaf6022c6d862a1a2de185c

**Comment by starbelly** [comment]
Yeah, agreed on the phoenix part. It's not exactly relevant to the project. The phoenix parts are things you need to know for using phoenix and postgres in docker containers in general 👍

**Review by starbelly — APPROVED** [review]

**Comment by paulo-ferraz-oliveira** [comment]
Cool. I'm squash-merging, then.

**Pull request merged**
