### PR TITLE
Update OTP-25 to working version in readme

### PR DESCRIPTION
**Pull request by kianmeng**
See https://github.com/erlef/setup-beam/pull/118

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Hey, @kianmeng. Thanks for this. It seems the tests don't fully cover your changes, though, in terms of base container. Could you probably add some so they do?

**Comment by kianmeng** [comment]
@paulo-ferraz-oliveira You meant tests in this file, https://github.com/erlef/setup-beam/blob/main/__tests__/setup-beam.test.js for OTP 25?

**Comment by paulo-ferraz-oliveira** [comment]
Sorry, yeah, I should've been more explicit. They should be added to https://github.com/erlef/setup-beam/blob/main/.github/workflows/ubuntu.yml, one entry Ubuntu / Erlang version, where they don't exist. Thanks.

**Comment by kianmeng** [comment]
@paulo-ferraz-oliveira Done. By the way, do we have any sorting order for the matrix combo in https://github.com/erlef/setup-beam/blob/main/.github/workflows/ubuntu.yml?

**Comment by paulo-ferraz-oliveira** [comment]
Hi, @kianmeng. I'll make the actions run. No particular sorting order, I believe. Thanks.

**Comment by paulo-ferraz-oliveira** [comment]
Thanks for your update, @kianmeng. Merging...

**Comment by kianmeng** [comment]
:partying_face: :partying_face: :partying_face: :partying_face: :partying_face:

**Pull request merged**
