### PR TITLE
Ease pre-pull request fork CI as well as github-actions based dispatch

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
# Description

We allow GitHub actions pull requests to dispatch the other workflows when version updates are in order.

We also simplify the other conditions to be simply "on push".

- [x] I have performed a self-review of my changes
- [x] I have read and understood the [contributing guidelines](/erlef/setup-beam/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
@starbelly, don't really understand why CI isn't running. It's either basing itself on the new conditions (which are "all push", so should work) or the previous conditions (which included "pull request to main", so should work). I believe you can "trust it", and approve+merge. We can later see if it runs in `master` or not, and try to bugfix it, if not.

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira I've experienced this before :( Nothing to do with this action AFAIK. What you can do is push an empty commit to give it a jiggle as FYI.

**Review by starbelly — APPROVED** [review]
I'm happy to trust approve this one 😄 There must be _some_ trust in this world ❤️

**Comment by paulo-ferraz-oliveira** [comment]
There it goes, queue in `master`

image

❤️

**Pull request merged**
