### PR TITLE
update checkout to v4

### PR DESCRIPTION
**Pull request by lordB8r**
# Description

Updated checkout to most current version (v4)

- [x] I have performed a self-review of my changes
- [x] I have read and understood the [contributing guidelines](/erlef/setup-beam/blob/main/CONTRIBUTING.md)

### CODE REVIEW

**Comment by starbelly** [comment]
Not sure why this isn't running, also need to understand what v4 gives us and issues with v3.

**Comment by paulo-ferraz-oliveira** [comment]
I'm also curious about the need for this change... I don't see any reports on security-related issues, or deprecations.

**Review by paulo-ferraz-oliveira — CHANGES_REQUESTED** [review]
Check the comments above.

**Comment by paulo-ferraz-oliveira** [comment]
I'm closing without merging for lack of response and because we don't see the need to do this, at this moment.

**Pull request closed without merging**
