### PR TITLE
Increase consumer confidence

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
I'm trying to test with more Ubuntus. I'm not sure any will fail, but will analyse results if they do.

This is a draft, for the time being, which may change if #31 gets merged to `main`.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
I'll keep this in draft until we decide on #31.

**Comment by ericmj** [comment]
I think this is overkill, we don't need 71 checks. Testing a few OTP version, Elixir versions, and each OS version is enough. We don't need to test every combination on every OS version. If we want to test selecting of versions it would be better to unit test that.

**Comment by paulo-ferraz-oliveira** [comment]
It is overkill, I agree, though it's not every combo in every OS :) We are already unit testing selection of versions, supposedly well enough. I'll trim it down.

**Comment by paulo-ferraz-oliveira** [comment]
I'll mix this with #31. The concept has been proven and marginally accepted.

**Pull request closed without merging**
