### PR TITLE
Have rebar3.cmd work on a Windows CMD shell

### LINKED ISSUE #147: Have rebar3 + rebar3.cmd work on a Windows CMD shell
Hello!

The rebar3 documentation recommends creation of a `rebar3.cmd` file so that rebar3 can be run from the shell.

https://rebar3.readme.io/docs/getting-started

> copy rebar3 file to %USERPROFILE%\bin
> make a file using notepad.exe with the contents of the .cmd invoker for escript to run rebar3 (provided in this document below)
> open a new command-line and type rebar3

```batch
@echo off
escript.exe "%~dpn0" %*
```

setup-beam doesn't do this which I believe results in Gleam's Windows workflows to fail when it attempts to call rebar3.

Could we also create this file?

Thanks,
Louis

### PR DESCRIPTION
**Pull request by paulo-ferraz-oliveira**
Closes #147.

@lpil

### CODE REVIEW

**Review by lpil — APPROVED** [review]
Wonderful, thank you!

**Comment by paulo-ferraz-oliveira** [comment]
I will still want to add a Rust -specific case, as we briefly discussed before, to see if this fits the bill.

**Comment by paulo-ferraz-oliveira** [comment]
Added a Rust-specific test case, but `rebar3`'s executable cannot be found: https://github.com/erlef/setup-beam/actions/runs/3308594785/jobs/5461095772#step:10:20... even though it can from shell `cmd`. 😕

**Review by starbelly — APPROVED** [review]
Very nice 😎

**Comment by paulo-ferraz-oliveira** [comment]
It would be even nicer if I could understand why Rust can't find the executable, but the shell it runs on can. I'll try to find some time to continue this today, at night.

**Comment by paulo-ferraz-oliveira** [comment]
Even though [this](https://github.com/erlef/setup-beam/actions/runs/3314047898/jobs/5472823100#step:8:2) seems to be working, it's not. Look at `cargo test`... it's not being run.

**Comment by paulo-ferraz-oliveira** [comment]
@lpil, from Rust, for example,

```
process::Command::new("cmd").args(&["/C", "rebar3"])...
```

can, as of this pull request, at least, find `rebar3`. (my understanding is that `process::Command` does not run inside a shell or consult `PATH`, so workarounds are required)

Another possible way to do it is

```
let where_is_rebar3 = env::var("INSTALL_DIR_FOR_REBAR3").unwrap() + "/bin/";
process::Command::new(where_is_rebar3 + "rebar3.cmd").arg("version")...
```

for example. Let me know if this is enough (you can also test with this branch and find out if you need to adjust).

**Comment by paulo-ferraz-oliveira** [comment]
But, in that case, would 

```
process::Command::new("cmd").args(&["/C", "rebar3"])...
```

be suitable?

Can you give me an example (either on GitHub or by pasting code here) of what you're actually using? That way I can hack it until it passes 😆 (not your code, but mine).

**Comment by lpil** [comment]
It would not, we don't spawn a shell to run subprocesses for any other program.

**Review by starbelly — CHANGES_REQUESTED** [review]
Waiting for env var issues to be sorted out.

**Comment by paulo-ferraz-oliveira** [comment]
Force pushed to rebase onto `main`.

**Comment by paulo-ferraz-oliveira** [comment]
Hey, @lpil.

I've been trying to update this pull request with different degrees of sustained frustration. Let me know if [this](https://github.com/erlef/setup-beam/pull/151/files#diff-59fd5fb931e4cd2a28dbb9c558b11a7ad54a3e552641a763e062e4e078735895R17) is enough (or maybe you can test the action as-is, from this branch - just use `paulo-ferraz-oliveira/setup-beam@feature/rebar3.cmd` instead of `erlef/setup-beam@...`), or otherwise suggest a change to the test so that we can potentially move forward.

I'm not Rust savvy so don't actually understand what's preventing this from working as expected.

The [result is apparently Ok](https://github.com/erlef/setup-beam/actions/runs/3528841439/jobs/5919346763#step:9:14), but there's the potential for the current implementation to not serve your needs.

Thank you.

**Comment by lpil** [comment]
Hi @paulo-ferraz-oliveira ! That looks perfect, thank you! 💜

**Comment by paulo-ferraz-oliveira** [comment]
Hey, @starbelly, I believe we're ready for review, finally 😄 

Have fun!

**Review by starbelly — APPROVED** [review]
🥳

**Comment by paulo-ferraz-oliveira** [comment]
Merging... @lpil, let me know if you'd require a release for this, otherwise it can wait a while longer for the other open pull request to get merged in too...

**Pull request merged**
