### PR TITLE
Update for latest Gleam

### PR DESCRIPTION
**Pull request by lpil**
- Gleam releases now use LLVM triplets for platforms so the download
  URLs have been updated accordingly.
- Gleam's rebar3 support has been removed.

This change means that future versions of this action cannot download
older versions of Gleam. I can make it backwards compatible, but I will
need help from someone who can convert the shell script into PowerShell
for Windows.

### CODE REVIEW

**Comment by paulo-ferraz-oliveira** [comment]
Hi, @lpil.

I'd usually not worry about backward compatibility before 1.0.0 (following Semantic Versioning principles) - which is Gleam's case.

At the same time, if `rebar3`'s no longer support, would it be better to remove `rebar3-version` from the Gleam combos, everywhere?

Cheers.

**Comment by starbelly** [comment]
> This change means that future versions of this action cannot download
> older versions of Gleam. I can make it backwards compatible, but I will
> need help from someone who can convert the shell script into PowerShell
> for Windows.

This is an interesting one... does a backward incompatible change for a supported language mean that we break compatibility for users and thus need to bump the major version? It may be the a big note in the README.md is good enough. 

I'm not 100% sure on this on tbh. I tend to think that since our API has not changed, then we do not need to bump the major. To  boot, gleam is not 1.0 yet, thus it should be somewhat expected, no? 

Thoughts?

**Comment by lpil** [comment]
I already have the code for backwards compatibility using shell, so I could add that and we leave windows support as a future addition?

**Comment by starbelly** [comment]
> I already have the code for backwards compatibility using shell, so I could add that and we leave windows support as a future addition?

That sounds quite amenable to me :)

**Comment by paulo-ferraz-oliveira** [comment]
@lpil, sure thing. Would you create an issue for what would need to be done, so somebody can take a look at it later? Cheers.

**Comment by lpil** [comment]
Fab! I've updated this PR and created the issue.

The build is failing but isn't printing any debug information. Is there a way to get more out of it? It passes for other installations so I'm not sure what might be happening.

**Comment by starbelly** [comment]
> Fab! I've updated this PR and created the issue.
> 
> The build is failing but isn't printing any debug information. Is there a way to get more out of it? It passes for other installations so I'm not sure what might be happening.

There's no gleam-0.23.0-rc1-linux-amd64.tar.gz for [v0.23.0-rc1](https://github.com/gleam-lang/gleam/releases/tag/v0.23.0-rc1)

**Comment by lpil** [comment]
Ah there it is! I found a typo in the script.

**Review by starbelly — APPROVED** [review]

**Comment by starbelly** [comment]
@paulo-ferraz-oliveira LGTM.

**Comment by lpil** [comment]
Oh yes! I forgot to remove the rebar bits. I have done that now

**Comment by paulo-ferraz-oliveira** [comment]
Merging... Many thanks, @lpil.

**Comment by lpil** [comment]
Wonderful, thank you! Would it be possible to get this released soon? I would like to start using new Gleam versions 😅

**Comment by starbelly** [comment]
> Oh yes! I forgot to remove the rebar bits. I have done that now

Yup, we certainly can 👍

**Comment by paulo-ferraz-oliveira** [comment]
I'll release and tag this today, and by then it'll also contain a pull request of mine 😄.

**Comment by paulo-ferraz-oliveira** [comment]
@starbelly, I'll move your tag, if that's Ok, since it was never released in any case...

**Comment by paulo-ferraz-oliveira** [comment]
v1.13.0 released, v1.13 tagged, v1 moved (to v1.13)

**Pull request merged**
